### ISSUE TITLE
Monte Carlo 2, after problem 1, up through problem 2

### ISSUE THREAD

**Issue by tannert** [Foundations-of-Applied-Mathematics/Labs#1018]
- typo: 'We X and Y in this way'

- typo: 'We chose a different' should be 'We choose a different'

- I think it's misleading that Y is generated by g_X.  Why not make that f_Y or g_Y?

**Comment by tkchris93** [comment]
Done with tannert's edits

**Comment by cassief2** [comment]
In Problem 2 it was a little unclear if we are supposed to use the gamma distribution for both the target distribution and the importance distribution.
