### ISSUE TITLE
Profiling feedback: up through problem 1

### ISSUE THREAD

**Issue by tannert** [Foundations-of-Applied-Mathematics/Labs#1022]
- ‘using Cython and Numba and other tools’ should be ‘using Cython, Numba, and other tools’
- Plz no title case in the bulleted list under ‘How To Optimize’
- You might want ‘determined by the loops’ to be ‘determined by its loops’
- ‘Nested loop quickly increase’ should be ‘Nested loops quickly increase’
- It doesn’t look like generators are covered anywhere in the intro labs.  Instead of just including a link to the documentation for generators, what if we wrote a short section on them and then included a short problem 1 where you build a generator that returns fibbonacci or prime numbers?  You could then also have the student profile it and show that it runs much faster than a more naive approach.
- in the code block in problem 1, you need to standardize my_list and mylist.
- ‘much closer than compiled languages’ should be ‘much slower than compiled languages’

**Comment by tkchris93** [comment]
I have changed everything @tannert pointed out except for the section on generators. Work in progress. I think there's a whole lab on generators hiding somewhere. Most of the examples I can think of don't make enormous changes in runtime, but I'll mess with it a bit more.
