### ISSUE TITLE
Profiling feedback: after problem 1 up through problem 2

### ISSUE THREAD

**Issue by tannert** [Foundations-of-Applied-Mathematics/Labs#1023]
- In the compilation from the command line section, it says ‘setup.py’ was discussed earlier in the lab but it wasn’t
    - Perhaps this is related - when you bring up cymodule.pyx for the first time, you don’t explain what it is at all - is it a system file, or the py file you’re working on?
    - I tried to get compilation to work with what’s in the lab right now and I couldn’t - I need to know more about setup.py
- In the part about type declarations, can you explain better why declaring j to be an int is useful, while doing the same to i is not?
- The paragraph that starts with “After modifying cymodule.pyx” has tighter line spacing than the rest of the document

**Comment by cassief2** [comment]
-Something that might be good to address in either the pdf or spec file is how we want to put the cython and numba code in the solutions.py
-When comparing the different functions in problem 2, you may want to specify what results we are printing to the terminal. (i.e. if we are just printing the different speeds)

**Comment by shanemcq18** [comment]
@tkchris93 is this all old feedback or would it still be useful to have around?
