### ISSUE TITLE
Profiling feedback: after problem 3 up through problem 4

### ISSUE THREAD

**Issue by tannert** [Foundations-of-Applied-Mathematics/Labs#1024]
- Have function decorators been covered yet?  You use one in the Numba section but I’m not sure I know what they are exactly

**Comment by cassief2** [comment]
In section “More Control Within Numba” in the third paragraph in the sentence right before the yellow box, change ‘Note that is necessary’ to “Note that it is necessary”

**Comment by shanemcq18** [comment]
Function decorators were never covered and we don't actually have a place for them. Should that be in an "Additional Material" section of the first lab or something? We could do this with several of the intro labs to fit in the topics that never really seem to fit in (Matplotlib/Mayavi additional material: animation; OOP additional material: static methods; Exceptions additional material: assert statements; etc.)

For now, we shouldn't worry too much about it. You can go online and learn the idea behind decorators in about 2 minutes.

**Comment by shanemcq18** [comment]
@tkchris93 is this all old feedback or should we keep it around for a little while longer?
