### ISSUE TITLE
Unit Test 

### ISSUE THREAD

**Issue by Mylancook** [Foundations-of-Applied-Mathematics/Labs#1036]
Give feedback for Unit Test lab

**Comment by shanemcq18** [comment]
Needs a little section about the "assert" statement. It's easy but we can't assume people know it yet.

assert <statement>, "message"
Raises an AssertionError with error message 'message' if <statement> is false.

**Comment by tannert** [comment]
Added an info block about the assert statement.

**Comment by shanemcq18** [comment]
This lab will be revisited in Spring / Summer 2016. We should consider making it more of a testing lab instead of just unit testing. Perhaps we have a section on unit testing, a section on debugging, and then give them some very carefully sabotaged code to fix.
