### ISSUE TITLE
Standard Library Final Draft

### ISSUE THREAD

**Issue by shanemcq18** [Foundations-of-Applied-Mathematics/Labs#1120]
- [x] Table formatting: take out lines between entries.
- [x] **Problem 4** needs to do the following:
- [x] Rework the section to match the new problem 4.
- [x] Warning about running vs importing (mentioned below)
- [x] Proofread Shut the Box
- [x] Proofread / fix "Additional Material" section

New Problem 4: Shut the Box
- We provide a module that has functions to:
    - Pass in the list and numbers to remove from it, then return the list with the numbers removed
    - Pass in a number and the list, return `True` if there is a valid move, `False` otherwise
    - Parse command line input and return a list of corresponding integers (return empty list if invalid)
- They have to:
    - Dice roll with `random.randint()`
    - Print the current state of the game
    - Keep track of remaining numbers and scores
    - Get command line input with `raw_input()`
    - Check if command line input sums to dice roll
    - Keep track of the game's end, report result
    - Get command line arguments for player names using `sys.argv`

**Comment by montu-byu** [comment]
Here is the Youtube video
https://www.youtube.com/watch?v=vLlZGBQ6TKs

**Comment by shanemcq18** [comment]
Need a **Warning** box at the end of _Running and Importing_ about how `import` doesn't work twice. Prefer `run` in IPython (but don't talk about the `reload` function): Example of running a file, discovering an error, fixing it, rerunning the file, lo and behold it is now fixed in the namespace (but importing twice won't work)

**Comment by davidreber** [comment]
I just proofread the second half-ish of the lab, and did the "shut the box" problem, as requested by @shanemcq18. 

I think the lab is great! It covers the main concepts of the Python standard library simply and thoroughly enough.  Consequently, the only feedback I have are very minor and semantic:
    - In the "Achtung!" warning box, you could modify the sentence which introduces the `run` command to explain that you can use it from the start - you don't need to run the `import` command first in Ipython.
    - In the third code box in the `sys` module section, `if len(sys.argv) != 2: print("An extra command line argument is required") ` assumes that `len(sys.argv)` is equal to 1, because it doesn't deal with cases where more than 2 arguments are given. So you could just say `if len(sys.argv) == 1`, since that's what you really mean.

The "shut the box" problem was a more challenging problem which will likely take some time and thought from students, but in a non-tedious, entertaining and entirely awesome way. It was a great wrap-up problem, synthesizing a lot of seemingly disconnected library concepts. I really enjoyed it!

**Comment by shanemcq18** [comment]
@davidreber would you take a quick look at this lab one more time? I just want your opinion on a few things, all in the "Additional Material" section:
- The code box under "More Built-in Functions." Let me know if it's helpful.
- The explanation of the rules for the Two-Player Shut the Box game. Does it make sense?
- The whole "Python Packages" section. I looked into it a little more, learned some stuff, and fixed it. I think it's important and better explained, but it's also longer now. Let me know what you think.

We are VERY CLOSE to final drafting this thing.

Also @montu-byu you also might want to look at the little Two-Player Shut the Box explanation to see if it is satisfactory.

**Comment by davidreber** [comment]
@shanemcq18 
- The code box under "More Built-in Functions":
    - In the sentence before the code box, I think you mean "when used in conjuction _with_ conditionals or list comprehensions.
    - For the third part (checking that none of the numbers are even), it's simpler to check that all the numbers are odd. So, for this example, we're going to have to choose between a slightly more complicated implementation (as in current problem, which is a simple example), or a slightly more complicated example (say, checking that none of the integers are divisible by 3, for which this example is in fact the simplest implementation).  I would lean toward the slightly more complicated example so that we don't justify bad coding, but that's the trade-off.

- Two-Player Shut The Box:
    - "If _the first player_ fails to shut the box, the second player begins a round...". Otherwise when first reading it, it sounds like 'if they (both the first and second players) fail to shut the box, the second player begins a round....'.
    - This section is kind of confusing. I would help reword it, but I'm not sure I even understand the rules. It's a cool idea though!

- Python Packages:
    - I like the SSB!
    - The comma at the end of "Use the syntax...to load a module within a subpackage" should be a period.
        - I'm getting confused by the names referenced in that  paragraph. 
    - Maybe change the print statements into just title comments (or like, `# Inside __init__.py`
    - In sentence "To access code in a file...", `import` was misspelled as `imort`

**Comment by shanemcq18** [comment]
New 2p shut the box explanation:

Consider modifying your shut the box program so that it pits two players against each other (one player tries to shut the box while the other tries to keep it open).
The first player plays a regular round as described in Problem \ref{prob:shut-the-box}.
Suppose he or she eliminates every number but 2, 3, and 6.
The second player then begins a round with the numbers 1, 4, 5, 7, 8, and 9, the numbers that the first player had eliminated.
If the second player loses, the first player gets another round to try to shut the box with the numbers that the second player had eliminated.
Play continues until one of the players eliminates their entire list.

**Comment by shanemcq18** [comment]
Time to move on! :octocat:
