### ISSUE TITLE
Lab: Getting Started

### ISSUE THREAD

**Issue by shanemcq18** [Foundations-of-Applied-Mathematics/Labs#1121]
- [x] Objectives: Ignore references to future labs, better motivation.
- [x] Take out the bullet points at the beginning ~~or explain them better~~.
- [x] Explain terms like IDEs, Interpreter, etc.
- [x] Shorten discussion on different IDE options. Give them one way to do it -- use a text editor with IPython. We'll introduce Jupyter later.
- [x] need explanation of `and`, `or`, and `not`
- [x] Examples of `and`, `or`, and `not` with `if` statements
- [x] **Problem 4** is problematic. Specifiy the input or give an example.
- [x] Replace **Problem 6** with Project Euler palindrome problem
- [x] Minor grammatical edits, etc.

- [x] Secondary review with professors (scheduled for Thursday May 19th).
- [x] Final touches post-meeting

**Comment by shanemcq18** [comment]
Possible new **objective** statement:

_Python is a powerful general-purpose programming language._
_As an interpreted language it can be used interactively, allowing for very rapid development._
_Python also has many powerful scientific computing tools, making it an ideal language for applied and computational mathematics._
_Thus in today's technology-oriented economy, a thorough understanding of Python opens many doors to potential careers and makes many bleeding-edge technologies accessible._

_In this introductory lab we introduce Python syntax, data types, functions, and control flow tools._
_These basics will be an essential part of every problem, algorithm, and program in this curriculum._

Comments, @jhumpherys ?

**Comment by shanemcq18** [comment]
For next time: how should hints be included? With parentheses, indented, how?

**Comment by shanemcq18** [comment]
Is _Getting Started_ really the title for this lab, or should it be called _Introduction to Python_ or _Python Basics_ or something?

**Comment by shanemcq18** [comment]
Project Euler problem: rephrase so "simple but challenging"

**Comment by shanemcq18** [comment]
This lab is now in the _final draft_ stage. It will need to be modified when we switch to Python 3, but that's it.

**Comment by jhumpherys** [comment]
Python is a powerful general-purpose programming language that can
also be used interactively and allow for rapid development.
Additionally, python has many powerful scientific computing tools,
making it an ideal language for applied and computational mathematics.

In today's information economy, a thorough understanding of Python
opens many doors to potential careers and makes many bleeding-edge
technologies accessible.

In this introductory lab we introduce Python syntax, data types,
functions, and control flow tools.  These basics will be an essential
part of every problem, algorithm, and program in this curriculum.
