### ISSUE TITLE
UNIX Shell [Summer 2016]

### ISSUE THREAD

**Issue by jadams1988** [Foundations-of-Applied-Mathematics/Labs#1164]
Beginning to look at UNIX Shell lab. First issue I have come across is that Windows users may not understand what is being asked, since they don't have a Terminal, only the Command Prompt which uses different key words. So we need to start out by making a distinction for users of different operating systems. Make Windows users download some Shell they can use. Since they already downloaded GIT Bash from the start, they could probably just use that.

Another issue is there are files which have not been put into the repository or on ACME yet, namely whatever files this lab needs the student to download. I have a copy of the files from Chris, we just need to get them, put into the system.

**Comment by shanemcq18** [comment]
At the beginning of Shell 1 there's a big **Note** box that looks like it got a sentence cut off. Also @jaredawebb have you finished revising this edition of Shell 1?
