### ISSUE TITLE
Image Segmentation [Summer 2016]

### ISSUE THREAD

**Issue by jmorrise** [Foundations-of-Applied-Mathematics/Labs#1166]
Dr. Evans pointed out that although this lab is part of Volume 1, graph theory is not covered in Volume 1. The graph theory here is pretty basic, but we still need to make sure that anything about graphs is defined/explained.

- Revise the Connectivity section
    - [x] Get rid of the "surprising" fact about the second smallest eigenvalue. This is actually a single case of a broader [result](https://en.wikipedia.org/wiki/Laplacian_matrix#Properties) that says that the number of zero eigenvalues equals the number of connected components in the graph. State this result and give intuition about why it is true (not the full proof).
    - [x] Define "connected component" 
    - [x] Include: The second smallest eigenvalue is called the "algebraic connectivity" of the graph
    - [x] Edit Problem 2 to reflect this
    - [x] Remove the "what do you notice" portion of Problem 2
    - [ ] Expand Problem 2 to be more substantial?
- Improve the explanation of the image segmentation algorithm
    - [x] Begin with a short outline of what the algorithm will accomplish (bullet points or numbering)
    - [x] Break up big blocks of text
    - [x] Bring out the main point of "Minimizing the Cut," right now it's buried in a pile of text
    - [x] Any other wording changes to make the explanation easier to follow
- Image segmentation code
    - [x] Make the `getNeighbors` code easier for the student to understand. It's a good utility to give the students and saves them time, but a tiny bit clunky. (Either change the code itself, or give a better explanation). 
    - [x] Give better directions on Problem 3 than "Hint: Vectorize"
    - [ ] Clear up any problems with the eigenvalue solver.
    - [ ] Ensure the solutions code is working correctly and reliably 
    - [ ] Test the code on images other than the example
- [x] Update spec file

**Comment by jmorrise** [comment]
Some things about eigenvalue solvers in this lab. @shanemcq18 not sure who would know about these.

- SciPy has two sparse linear algebra functions for computing eigenvalues, `sparse.linalg.eigs` and `sparse.linalg.eigsh`. `eigsh` is optimized for working with symmetric matrices, and the Laplacian matrices we care about are symmetric, but the old code uses `eigs` instead. I'm not that knowledgeable about eigenvalue solvers. For someone who is, any reason we shouldn't switch to `eigsh`?
- The library that SciPy is wrapping, ARPACK, often fails to converge on test cases. It seems to be because ARPACK has trouble finding the smaller eigenvalues, which we want. Are there any methods optimized for finding small eigenvalues?

**Comment by shanemcq18** [comment]
@montu-byu might be the best one to ask. I'll bring it up in the next meeting.

**Comment by shanemcq18** [comment]
@jmorrise I ran into the same ARPACK problems when I was poking around with sparse matrices for a different lab. @montu-byu thoughts?

**Comment by tannert** [comment]
Should we fix broken links to other labs?  For example in problem 1.
In the 'connectivity - first application of laplacians' section, it says 'Clearly the rows of L must sum to 0 (why?)'.  Is that a cue to the editor to put in an explanation, or a cue to the reader to consider their understanding?

**Comment by tannert** [comment]
Is it ok to use didactic questions like 'Why is this true?' before starting an explanation?  I'm trying to make some of the more unintuitive stuff a bit easier to digest - starting with the bit where it explains why unconnected graphs have multiple zero eigenvalues

**Comment by jmorrise** [comment]
What other lab is there a broken link to?

First question: was a cue to the reader, although you're right, not a great one. The Laplacian is L = D - A and since D is the row-sum of A, the rows of L sum to zero. 

Second: In that section I wasn't sure whether to just state the fact about eigenvalues, or to provide some kind of intuitive explanation. I went with the second option. Definitely feel free to improve it, but don't make it super long. The student should have to do some of their own thinking to grasp what's going on, and the explanation is just supposed to point in the right direction. About didactic questions - I think someone told me to keep them to a minimum once, but I'm not sure.

**Comment by jmorrise** [comment]
@tannert If you can think of a good way for Problem 2 to be more substantial, let me know.

**Comment by tannert** [comment]
@jmorrise in problem 1 it says "Hint: You can compute the diagonal of the degree matrix in one line by
summing over an axis (see Lab ??)."  Is that referring to the numpy lab?

**Comment by shanemcq18** [comment]
Notes for later:

- Clear up any problems with the eigenvalue solver.
- Ensure the solutions code is working correctly and reliably
- Test the code on images other than the example
