### ISSUE TITLE
Make sure one of the pandas labs includes the `isin` method

### ISSUE THREAD

**Issue by tkchris93** [Foundations-of-Applied-Mathematics/Labs#1167]
The `isin` method is super useful for selecting rows based on a list of acceptable values. It is equivalent to where ... in ... statements in SQL.
```python
# SELECT * FROM df WHERE "age" IN (14, 15, 19, 20)
df[df["age"].isin([14,15,19,20])
```

I don't believe this is in one of the labs yet, but I may be wrong.

**Comment by shanemcq18** [comment]
@Mylancook looks like this should go in Pandas I where it talks about SQL operations?

**Comment by Mylancook** [comment]
Got it.  Is there anything else (especially in the SQL-like section) that would be helpful to add in?

**Comment by shanemcq18** [comment]
@benehlert any thoughts?

**Comment by benehlert** [comment]
It seems like you added it.  That command sounds useful to me so I would add it as well.
