### ISSUE TITLE
SVD [Summer 2016]

### ISSUE THREAD

**Issue by jmorrise** [Foundations-of-Applied-Mathematics/Labs#1184]
This lab is in pretty good shape. All the information is there and the problems are good. The explanation of concepts needs to be organized a little better, and some of the problem statements need to be clarified.

- [x] Make introduction shorter and more to the point.
- Improve the initial explanation of the SVD
    - [x] Reference the textbook for the existence theorem (how do you reference the book??)
    - [x] Remove math/proofs that they can find in the book but won't use in lab (e.g., how to use Gram-Schmidt to find the decomposition of the null space)
    - [x] Revise and organize for clarity
    - [x] Add note about how calculating A^HA is numerically unstable
- Problem 1 - calculating the SVD
    - [x] Solutions code doesn't remove the zero singular values correctly. Fix.
    - [x] Edit problem description
- [x] Problem 2 - visualizing the SVD - improve motivation and problem statement
- [x] Condense the multiple short subsections after problem 2 and organize their content in a logical fashion. They feel disorganized. The idea of a best low-rank approximation is in there, but needs to be clearly stated.
- [x] Problem 3 is fine.
- [x] Problem 4 - edit lead-up explanation and statement.
- Problem 5 
    - [x] Edit and test code
    - [x] Organize hints in problem statement 
- [x] Update spec file
- [x] Final proofread by @tannert

**Comment by jmorrise** [comment]
@shanemcq18 How does one put a reference to the textbook in the lab? Can we do this?

**Comment by shanemcq18** [comment]
Good question. I'll bring this up on Thursday.

**Comment by shanemcq18** [comment]
@jmorrise since the book is fluid, the most specific you can get is referencing a chapter. So maybe you just say something like, "for more details, see chapter 4 [that's where SVD stuff is] in the text."

**Comment by shanemcq18** [comment]
@jmorrise All done with this one?

**Comment by tannert** [comment]
In the Low-Rank Matrix Approximation section, the lab says 'Larger singular values correspond to columns of U and V that contain more information', but it never explains why.  Should we elaborate on that, or maybe explain it in an earlier section?

**Comment by shanemcq18** [comment]
Only thing left: decide whether or not this should be a notebook.

**Comment by shanemcq18** [comment]
Notes for later:
- Needs a better objective statement
- Could use a diagram showing the differences between the full, compact, and truncated SVD, similar to the diagram in QR 1 showing full and reduced QR
- Remove the use of `circle.npz` in Problem 2 and instead have them make a circle out of polar coordinates
- Names of functions should be followed by parentheses (`svd` --> `svd()`)
- Move Figure 1 to be closer to where it is needed (`\begin{figure}` --> `\begin{figure}[H]`)
- Clean up repository folder
