### ISSUE TITLE
Bokeh First Draft Progress

### ISSUE THREAD

**Issue by tkchris93** [Foundations-of-Applied-Mathematics/Labs#1188]
### Introduction
- [x] Introduction 
- [ ] Provide a link with the finished project so they can see what they are working towards.

### Cleaning the Data
- [x] Introduce dataset.
- [ ] __Problem__: create `accidents` DataFrame
      - [x] Write problem
      - [ ] Make a table of what `accidents.head()` should look like.
- [ ] __Problem__: create `drivers` DataFrame
      - [x] Write problem
      - [ ] Make a table of what `drivers.head()` should look like.
      - [ ] Provide students with `fars.zip` file.
      - [ ] Provide students with `id_to_st.pickle` file.

### Basic Plotting
- [ ] Marker Glyphs (Circle and Square)
      - [x] Explanation
      - [x] Code examples
      - [ ] Pictures with example output. 
- [ ] Patch Glyphs
      - [x] Explanation
      - [x] Code examples
      - [ ] Pictures with example output.
- [x] ColumnDataSource Object
      - [x] Explanation
      - [x] Code examples (replicate earlier figures)
      - [x] Make reference to earlier figures
- [x] __Problem__: draw state border lines
      - [x] Write problem
      - [x] Fix Michigan (at least) in the data set.
      - [x] Provide students with `state_borders.pickle` file
- [x] __Problem__: draw dots at the location of each fatal accident.
      - [x] Write Problem
- [x] Speeding up Interactions with WebGL
      - [x] Explanation
- [x] __Problem__: Add WebGL support to figure (super easy problem)
      - [x] Write Problem.
- [ ] Laying Out Plots

### Basic Charts
- [ ] __Problem__: a little more data cleaning.
      - [x] Write problem.
      - [ ] Make a table of what `counts.head()` should look like.
- [ ] Bar Charts
      - [x] Explanation
      - [ ] Code example (simple)
      - [ ] Code example (stacked) (give them the code for speeding accidents)
      - [ ] Pictures with example output
- [x] __Problem__: stacked bar chart for drunk driving
      - [x] Write Problem

### Adding Tooltips to Visualizations
- [x] Introduction
- [ ] Picture of an example tooltip
- [ ] Adding Tooltips to Bar Charts
       - [ ] Explanation
       - [ ] Code Example
- [ ] Adding Tooltips to Patch Glyphs
       - [ ] Explanation
       - [ ] Code example
- [ ] __Problem__: creating the necessary lists for the tooltips 
       - [ ] Write Problem
- [ ] HoverTool and Tooltips
       - [ ] Explanation
       - [ ] Code example
- [ ] __Problem__: add tooltips to the map plot
        - [ ] Write Problem

### Adding More Complicated Interactions
- [ ] Introduction
- [ ] Widgets
- [ ] Sliders

### MORE STUFF COMING SOON...

**Comment by tkchris93** [comment]
After the meeting last week a lot of this stuff is not making it into the lab, so I'm going to create a new issue with the stuff that still needs to be done (images, most importantly)

**Comment by shanemcq18** [comment]
Closing in favor of #1212.
