### ISSUE TITLE
Bokeh [Summer 2016] (2)

### ISSUE THREAD

**Issue by tkchris93** [Foundations-of-Applied-Mathematics/Labs#1212]
- [x] Add table for accidents.head()
- [x] Add table for drivers.head()
- [x] Circle glyph figure
- [x] Circle glyph w/ colors figure
- [x] Square glyph figure 
- [x] Triforce figure
- [x] Hover/Tooltip figure
- [x] Color states figure
- Figure out how to host the complete example. https://github.com/bokeh/demo.bokehplots.com 

If hosting this ends up being too much work (though it would be nice to have it this way), I should be able to replicate the functionality using a static html file. It would be a little bit of a pain to get it to that state, but we shall see. If I do a static version, I could put it on friedrich or whatever way we do the ACME website.

**Comment by shanemcq18** [comment]
Note: this is a continuation of #1188.

**Comment by shanemcq18** [comment]
Notes for later:
- Figure out how to host the complete example. https://github.com/bokeh/demo.bokehplots.com
