### ISSUE TITLE
Where to introduce Jupyter Notebook

### ISSUE THREAD

**Issue by jmorrise** [Foundations-of-Applied-Mathematics/Labs#1227]
This thread is to discuss where would be the best place to first introduce the iPython/Jupyter notebook format. Current candidates seem to be Image Segmentation, SVD, Facial Recognition, and Data Visualization. Last year it was introduced with Facial Recognition. This worked great for some students and was confusing to others for the reasons explained below.

My vote would be to introduce it at SVD, and then optionally allow students to turn in Facial Rec as a notebook (maybe with extra credit offered). The test driver presents a problem. Any ideas on how to test code that was submitted as a notebook?

Also, @shanemcq18, is there a master list of labs to be assigned as notebooks?

**Image Segmentation**
- Pros:
    - Earliest possible place to introduce the new format, so students get used it sooner. (Maybe with the option to use it for Facial Rec or SVD if they choose.)
- Cons:
    - Despite the title, it's not actually very image heavy. Only one image is displayed at the end. The beginning half of the lab doesn't have anything to print or display.
    - The math doesn't lend itself to practicing LaTeX
    - Can't run a test driver on a notebook

**SVD**
- Pros:
    - Plot and image heavy (a visualization problem, an image compression problem, and opportunity to show more images in the explanations)
    - There's plenty of math to practice LaTeX-ing equations, but not an overwhelming amount (they could LaTeX things like the definition of the SVD, but wouldn't need to go much beyond that)
    - The problems build on each other throughout the lab, which makes the notebook layout intuitive. In one cell they would write a function to take the SVD, and in a later cell they would use it to compress an image.
- Cons:
    - Can't run a test driver on a notebook. Problem 1, at minimum, needs a test driver.

**Facial Recognition**
- Pros:
    - Very image heavy lab with the potential to look really nice as a notebook
    - Don't really need to run this lab through a test driver
- Cons:
    - Solutions are structured as a class. The class has to be written all in the same cell. The students had to split up the methods across multiple cells, then recombine them at the end. Some had no problem with this; other got thrown off.

**Data Visualization** _(note: this lab will be turned in as a notebook irregardless)_
- Pros:
    - It's data visualization - the entire thing is plots. Might make for a less confusing first look at notebooks, since it obviously lends itself to the format.
- Cons:
    - This is the latest possible place to introduce the notebook; the students wouldn't have the option to use it for any of the above labs

**Comment by shanemcq18** [comment]
I still don't have any viable ideas for using test drivers on notebooks. If we try to make a notebook testable, it defeats the presentation aspect of the whole thing.

A proposed list of Jupyter Notebook labs:
#### Volume 1
- Image Segmentation
- SVD
- Facial Recognition
- Data Visualization
- Complex 1

#### Volume 2
- Fourier 1 (w/ sound files embedded in Notebook)
- Fourier 2
- Wavelets

Also, none of the Volume 3 labs, probably all of the 3B homework assignments, and probably all of the Volume 4 labs.

**Comment by jmorrise** [comment]
I don't think it makes sense to test a notebook either. Maybe ask the students to submit a .py file of some or all of their code?

That's a pretty good list to start. Interesting that the Volume 4 labs will be notebooks, but I guess that would make sense.

I actually don't think Image Segmentation is a good candidate; it's not really image heavy, most of the lab has nothing in it to plot or show, and it would be combining the first introduction of notebooks with a potentially confusing algorithm.

That would put Fourier 1 as the first place students see notebooks, which is also potentially confusing. 

Unless... we introduce it really early with the Matplotlib lab. That actually might not be a bad idea, as students would get used to it right off the bat. @shanemcq18 thoughts?

**Comment by shanemcq18** [comment]
We discussed that possibility today in the meeting, but it got shot down (at least for this year) because of time constraints. I personally think that it's important for students to learn how Matplotlib works outside of the notebook first, but a lot of others think introducing it with Matplotlib is a good idea. I also think it's too much too early to do that.

In any case, we'll have to introduce it with Fourier 1 or Image Segmentation. I think if Fourier 1 would work well with it we should do it. @Mylancook keep this in mind while you're working on Fourier.

**Comment by jmorrise** [comment]
Okay, and if it doesn't work well with Fourier 1 I think SVD would be an okay place to introduce it.

I wonder if the Linear Transformations lab would work? It looks like the new lab will still have a lot of plots. The timing functions in the second half might work differently with iPython notebook though, which might not be what we want. Not trying to interfere as I don't know that much about the new lab, just wondering.

**Comment by shanemcq18** [comment]
Let's scratch Image Segmentation off as a candidate then. We'll introduce it with Fourier 1 and SVD. I'll try to write an "introductory notebook" that serves as a demo to the notebook. I'll try to hit all of the points in [this demo](http://jupyter-notebook.readthedocs.io/en/latest/notebook.html).

**Comment by shanemcq18** [comment]
Verdict for Volumes 1 and 2:

A proposed list of Jupyter Notebook labs:
#### Volume 1
- SVD
- Facial Recognition (required)
- Data Visualization
- Complex 1

#### Volume 2
- Fourier 1 (w/ sound files embedded in Notebook)
- Fourier 2
- Wavelets

That means that Fourier 1 will probably be where the notebook is introduced, but we should keep in mind that schools only doing Volume 1 will see the notebook for the first time in SVD.
