### ISSUE TITLE
Page Rank

### ISSUE THREAD

**Issue by jmorrise** [Foundations-of-Applied-Mathematics/Labs#1261]
This is a pretty solid lab which shouldn't need any structure changes. The problem topics are good and the application at the end works well.

There are a few conflicts, however, that need to be cleared up.
- [x] **Sparse vs. dense** - The first problem uses sparse matrices, but the rest use dense. Either convert the whole lab to one or the other, or else motivate the choices of sparse vs. dense in the problems better.
- [x] **Vol. 1 vs. Vol. 2** - The lab assumes knowledge of Markov chains in several places, which is a Vol. 2 topic. The references to Markov chains need to be well explained, if they stay at all, and previous knowledge can't be assumed.
- [x] **Row stochastic vs. column stochastic** - Make it clear which we use when and why.
- **Eigenvalue solvers** - The issue has previously been raised that the eigenvalue solvers don't do an accurate job on this problem. This needs to get figured out.

Also, pertaining to the applications at the end:
- **Basketball data** - Several students last year asked if the data couldn't be presented in an easier-to-parse manner. I liked that they got a little practice sorting and organizing some data to make an adjacency matrix. But this could be something to consider.
- **Figure for Problem 5** - It would be awesome to have a figure of a graph describing the basketball application.
- [x] **SNAP** - The bit about SNAP datasets at the end is pretty underdeveloped. Could this provide some kind of look ahead to using data in a project? Maybe require the students to do something with it but leave it as an open-ended problem.

Other small fixes:
- [x] Edit objective
- [x] Update spec file
- [x] Remove confusing hint about sinks on Problem 3

**Comment by jmorrise** [comment]
Need to figure out where we keep the data for this problem - it isn't in the repository or on the ACME data webpage.

**Comment by shanemcq18** [comment]
This lab should definitely be Volume 2 independent, which means Markov stuff either needs to be explained from scratch or it needs to be taken out. I'll take a closer look at this soon.

**Comment by tkchris93** [comment]
I started looking into this lab a bit. I used the ncaa2013.csv dataset and the PageRank algorithm that comes with NetworkX and I got results that gave almost the same top 10, but different orders. Should we worry about this? I used the same damping factor for both.

**Comment by tkchris93** [comment]
Regarding references to Markov Chains, would it be okay to say something along the lines of "For those familiar with Markov Chains, Equation (whatever) defines a Markov Chain. PageRanks are simply the steady state of this Markov Chain." 

This way it doesn't depend on knowledge in any way, but it adds another level of understanding for those that have had Volume 2. Thoughts?

**Comment by tkchris93** [comment]
@shanemcq18 @jmorrise 
Here is my complete feedback. I want to run these ideas past you before I go making any changes.
- sparse vs dense. In this lab, the largest system we deal with is the NCAA data which is 347x347. That takes a nearly negligible amount of memory to store and we aren't in need of any kind of speed up, so I don't see the point (unless we do something with SNAP, but more on that in a second).
- Vol 1 vs Vol 2. As far as a graph-based algorithm, I think we do a pretty good job. I think we should add one sentence at the very beginning of the lab describing what a graph (and directed graph) is. For my thoughts on Markov Chains, see my previous comment.
- Row Stochastic vs Column Stochastic. I honestly have no idea why we need a column stochastic matrix. And the lab doesn't describe it either. If we just used column stochastic matrices throughout, we would have to mess with the traditional definition of the adjacency matrix, which I don't think is a good idea.
- Eigensolver. I wonder if there is some sort of instability going on. In my first comment on this thread, I mentioned that the iterative solver and the NetworkX version don't match up. If you compare the results of the iterative solver and the NetworkX, it's actually significantly closer than the iterative solver. Even if you make the tolerance tiny, the Eigensolver is significantly closer to the NetworkX version. (see more thoughts on NetworkX below)
- Basketball data. I remember this data being pretty frustrating as well. I know this would be just another thing to add to the lab, but I think there is a major case for introducing the NetworkX package. It's even easier if you throw the pandas csv reader at this problem as well, but that would be too far. We have the pattern of coding up a baby version then using the industry version. I think we should do that here too and just use the NetworkX solver for the basketball problem.
- Figure for Problem 5. The only thing that I can think of doing for a figure would be to plot the graph. But with a graph of more than 40 or 50 nodes, you get something called the bird's nest effect where your graph is just a jumble of lines all over the place. I can't think of any other alternatives.
- SNAP. I think this would be cool to include especially if we switch the basketball problem to NetworkX. We could have the students use a Twitter dataset to see which user is the most influential in the dataset. I also have a dataset of political blog citations, so we could see which blog is the most influential. If we don't use NetworkX, this will quickly merit using sparse matrices, which necessitates rewriting a few other pieces of code.

There are all my thoughts. I would love your feedback before I start tweaking things.

**Comment by shanemcq18** [comment]
@tkchris93 go ahead and start editing the lab. Here are my thoughts on the issues:
- Ignore sparse matrices in the main part of the lab and suggest using sparse matrices in the Additional Material section (we settled on a similar approach for the Markov Chains lab).
- I like the idea of mentioning the Markov stuff without going in depth.
- Let's go with row stochastic if you think it's better. I also though that the Markov Chains lab worked better as row stochastic, so this way they'll match. There's a note at the beginning of that lab that you might want to copy or allude to.
- ...so which is better, the iterative solver or NetworkX?
- Would it be a pain to do the basketball problem with the handmade solver and then have another problem with NetworkX? Either way, we should definitely use NetworkX. Doing it on Twitter data WOULD BE SO AWESOME.
- I have no guidance about the figure.

Email me if you have more specific questions.

**Comment by tkchris93** [comment]
False alarm on our algorithms not getting the same results as NetworkX. (#eggonface #nooberror) This is one of those situations that because of what I did, I'm shocked the answers were even close. Also good news, once fixing this problem now my iterative solver and eigensolver are giving the same answer. So all 3 now give the same answer.

**Comment by shanemcq18** [comment]
Leftover feedback from Jessica:
- **Eigenvalue solvers** - The issue has previously been raised that the eigenvalue solvers don't do an accurate job on this problem. This needs to get figured out.
- **Basketball data** - Several students last year asked if the data couldn't be presented in an easier-to-parse manner. I liked that they got a little practice sorting and organizing some data to make an adjacency matrix. But this could be something to consider.
- **Figure for Problem 5** - It would be awesome to have a figure of a graph describing the basketball application.
