### ISSUE TITLE
Remove plots from repository and generate at compile time

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#467]
We have a large number of pdf files in the repository. It would be better if we could have the plots generated when the lab manuals are built instead of including them as part of the repository. This would require some sort of plot building process. One option would be to have a global script that regenerates any plots that need to be updated. Another option would be to call the plotting scripts from the latex file in each lab. This doesn't need immediate attention, but it should probably be on our long-term outlook.

**Comment by shanemcq18** [comment]
Jeff requested more space for the repository (we previously have 1 Gig and he requested 10), so large files are a little bit less of a problem for the repo. Some plots also take a significant time to make, so recreating them every time a lab manual is compiled could really slow down compilation and development. We'll continue to explore the option over the summer though.

**Comment by shanemcq18** [comment]
See Issue #1214.
