### ISSUE TITLE
Revision of floating point lab

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#475]
The first floating point lab could use some revision. The class that they implement to trace precision is intriguing, but there have got to be better problems. Some ideas are stable polynomial evaluation and simulated quadruple precision arithmetic. Treffethen's linear algebra book has a good problem illustrating unstable polynomial evaluation. Something like that would be good.

For simple problems, we could also just have them code double precision and arbitrary precision versions of some simple code snippets that exemplify instabilities.

**Comment by shanemcq18** [comment]
Both of these labs were orphaned a long time ago. There is now a section in the Volume II textbook on Floating Point (including error).
