### ISSUE TITLE
Write a lab/introduction to git

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#479]
Git is currently proving to be a barrier to entry for some of the new contributors to this project. We need to either find or write a better tutorial so that they can get into the project a little easier. This could be in the form of a new lab, but it doesn't have to be. If we did make it a lab of some sort, it could later be added as part of the lab manuals if the need arises.

**Comment by shanemcq18** [comment]
We've decided (as of Jan 2015) to make a little appendix for Git. Someone needs to be assigned to this.

**Comment by shanemcq18** [comment]
See #1112 for the first draft.
