### ISSUE TITLE
Rewrite eigensolver lab

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#480]
The naive QR algorithm we use in the eigensolver lab is anything but robust. We can't expect students to code an industrial strength eigenvalue solver in two hours, but we can do better that what we have right now. Introducing shifts and chasing the bulge on the Hessenberg form of a matrix could be good things to add. The Givens rotations lab does add in some of the functionality that they should be able to use for something like that.

**Comment by shanemcq18** [comment]
See Issue #1241 for updates on the Eigenvalue finding lab. The things mentioned in this Issue might be good to put under the "Additional Material" section when discussing how to improve the QR Algorithm.
