### ISSUE TITLE
Prototype automated testing

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#496]
We should come up with some examples of ways to automate the testing of the solutions for the labs. Ideally, test cases could be included in each solutions template file so the students could check that their code works properly on their own. This could probably be done via a `if __name__ == '__main__':` block after all the prototypes for the different functions and classes.

**Comment by shanemcq18** [comment]
We're putting a `testDriver.py` file in each lab folder for whatever labs merit a test driver (others are better as Notebooks). Details on how to use them will be in the lab standards file and probably on the wiki for this repo soon.

**Comment by insertinterestingnamehere** [comment]
Way to go!
