### ISSUE TITLE
Review function signatures and descriptions in numerical differentiation and multi-deriv labs

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#497]
The lab on Newton's method relies heavily on code from previous labs. If students have not carefully debugged and reviewed their functions from the previous labs (the two numerical differentiation labs) the Newton's method lab becomes a nightmare for them to debug even though the algorithm itself isn't particularly difficult. We should update the problem descriptions and function signatures we give them for the earlier numerical differentiation labs so they reflect the use cases needed in the Newton's method lab.

These labs should also be prime candidates for adding tests as described in https://github.com/byuimpact/numerical_computing/issues/496 .

**Comment by shanemcq18** [comment]
The exercise where this is addressed is currently marked as optional (so we should decide what to do with that), but the issue remains.
