### ISSUE TITLE
Add Problems to CVXOPT lab.

### ISSUE THREAD

**Issue by abefrandsen** [Foundations-of-Applied-Mathematics/Labs#499]
I propose adding two problems to the CVXOPT lab: the L_1 minimization problem and the L_2 minimization problem. More specifically, 
   min ||x||_1
   s.t.  Ax = b
and
   min ||x||_2
   s.t. Ax = b.

The first problem can be stated as a linear program, and the second can be stated as a quadratic program. Both can be solved by methods in CVXOPT, and they are both important problems that come up later (such as compressed sensing).

**Comment by shanemcq18** [comment]
@swsuggs Sterling, you might want to think about this for the CVXOPT lab. I think we did this problem in the compressed sensing lab, but that lab is still very incomplete and in danger of dying. Would you bring this up in a meeting or talk to Jarvis/Jeff about it?

**Comment by shanemcq18** [comment]
Closing in favor of #1152
