### ISSUE TITLE
Backtracking

### ISSUE THREAD

**Issue by ayr0** [Foundations-of-Applied-Mathematics/Labs#522]
Backtracking is a fascinating approach used by several famous algorithms.  We already have labs on some of these algorithms, but none of them discuss the power of backtracking as a problem solving approach.  Classic examples of backtracking include depth-first search, breadth-first search, Dijkstra's algorithm, Hill Climbing, Kruskal's algorithm, and Prim's algorithm.

This would make a good metalab (i.e. an entire unit of labs).
http://en.wikipedia.org/wiki/Backtracking

**Comment by shanemcq18** [comment]
See #523
