### ISSUE TITLE
Pagerank revision

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#528]
The Pagerank lab is, unfortunately, still very rough around the edges.

Dr. Jarvis has suggested that we use the Pagerank algorithm to rank teams and create brackets for march madness.

The eigenvalue solver section needs to either use a different eigenvalue solver (sparse solver based on Arnoldi iteration?) or that approach needs to be switched out for a least squares based version.

There are also some issues in transitioning cleanly from the dense versions of the algorithms to the corresponding sparse versions. The descriptions should be rewritten so they are more conducive to sparce matrix operations. Of particular importance is the way we account for pages with no outbound links.

**Comment by shanemcq18** [comment]
See #1131 for the most recent version (as of today). @jmorrise is this issue old or still accurate?

**Comment by jmorrise** [comment]
Partly old. The problem about ranking teams has been added by me (could still use editing). The lab does transition from sparse to dense matrix operations in a confusing way. After an initial first problem using sparse matrices, dense ones are used for the rest of the lab. This should change.

I'm not sure how to improve the eigenvalue solver or how to switch that problem to a least squares approach.
