### ISSUE TITLE
Deprecation of UMFPACK in scipy.sparse.linalg

### ISSUE THREAD

**Issue by ayr0** [Foundations-of-Applied-Mathematics/Labs#582]
In SciPy .14, scipy.sparse.linalg was changed.

From the release notes:
The deprecated UMFPACK wrapper in scipy.sparse.linalg has been removed due to license and install issues. If available, scikits.umfpack is still used transparently in the spsolve andfactorized functions. Otherwise, SuperLU is used instead in these functions.

We need to make sure this doesn't break any labs using scipy.sparse.

**Comment by shanemcq18** [comment]
We've been having problems with `scipy.sparse.linalg.eigs()`. Is that related to this?
