### ISSUE TITLE
Unified Dataset Download

### ISSUE THREAD

**Issue by ayr0** [Foundations-of-Applied-Mathematics/Labs#601]
I propose having a unified dataset download as an archive.  It would reflect the directory structure of the current lab manuals.  This archive would be given to the students and would contain all datasets and templates for the labs.

**Comment by abefrandsen** [comment]
We now have 1TB or storage on a server where we can host datasets. Ryan, do you still have that data archive?

**Comment by shanemcq18** [comment]
see [acme.byu.edu/data](https://acme.byu.edu/data)

**Comment by shanemcq18** [comment]
See Issue #1214 for an update on this.
