### ISSUE TITLE
Add animation to earlier plotting lab

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#617]
Animation using Mayavi and Matplotlib is currently introduced in Volume 4.
We need to include it in the earlier lab on plotting.
For now we'll leave it in Volume 4 as well though, so that the students won't have to reference something they haven't been using consistently.

We should also work on including animations in earlier labs.
The spline labs would be good places to start, but they aren't currently included in our curriculum outline.

**Comment by shanemcq18** [comment]
This may be a good thing to put in the so-called "data visualization" lab (aka matplotlib 2). Any thoughts @Mylancook ?

**Comment by shanemcq18** [comment]
From #659 :
We slipped animation techniques for both matplotlib and mayavi in Volume 4. These animations are currently in a somewhat natural place, but if it is possible, it could be good to introduce it much earlier. Animations could (and should) then be integrated in to the later parts of Volumes 1 and 2.

**Comment by shanemcq18** [comment]
Animation should become Additional Material in the Data Visualization labs, but it should then be reintroduced in Volume 4 when it's closer to the usage.
