### ISSUE TITLE
Use the LinearOperator class in the Arnoldi and GMRES labs

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#627]
It turns out that SciPy does actually have an interface to their different Krylov methods that allows you to specify a generic matrix multiplication method.
The way to do this is to create an instance of the LinearOperator class.
All that is required is a function that performs matrix-vector multiplication and the shape of the appropriate matrix representation of the operator.
You will also need to set the data type attribute of the linear operator.

**Comment by shanemcq18** [comment]
@jmorrise you might want to see if this is still an option for those labs. Thoughts?
