### ISSUE TITLE
Updates to Poisson lab.

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#652]
There are two remaining todo items for the Poisson lab (at least in the immediate future)

- [ ] Mention that the code given works only for a square domain with the same spacing in both dimensions.
- [ ] Rewrite code examples to use the LinearOperator class and the built in versions of the GMRES and Conjugate Gradient algorithms.

This is a continuation of Pull https://github.com/byuimpact/numerical_computing/pull/626.

**Comment by shanemcq18** [comment]
@joshualy can you look at this? We can close it if it isn't up to date any more. I can't even remember doing this lab last year.

**Comment by joshualy** [comment]
@shanemcq18  This lab needs some major attention, but these really aren't the concerns that I have.  This lab was meant to address the problem of solving a steady state PDE in two spatial dimensions.  The application is really not very rigorous or especially interesting. It would be much more interesting to introduce the scattering problem using Helmholtz equation. This would mean rewriting most of the lab, and solving an entirely new problem. The scattering domain would probably be best given in polar coordinates, so the students would have to be guided through transforming Helmholtz equation, etc.
