### ISSUE TITLE
Revise IVP lab

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#655]
This is a continuation of https://github.com/byuimpact/numerical_computing/pull/593.
Here are the things that I currently remember needing to be fixed in the IVP lab.

- [ ] Revise variable ordering to match SciPy's `odeint`
- [ ] Introduce `odeint`
- [ ] Update solutions
- [ ] Make sure the variable naming scheme doesn't use the same thing to refer to different things.
- [ ] Add material that demonstrates that it is possible to obtain a more accurate solution with a higher order method. (This should show how a low order method's accuracy only increases to a point where the floating point error starts making smaller steps less accurate).

**Comment by shanemcq18** [comment]
@joshualy can you look at this? We can close it if it isn't up to date any more.

**Comment by joshualy** [comment]
@shanemcq18  I have just finished revising the IVP lab, and most of these comments are not applicable anymore.  It may be beneficial to introduce the students to odeint for the last problem in the lab though.
