### ISSUE TITLE
Revisions to heat flow lab

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#656]
This is a continuation of https://github.com/byuimpact/numerical_computing/pull/616.
The following items should be fixed in the heat flow lab.

- [ ] Add a diagram to explan how the updating process works.
- [ ] Add another diagram to show how the Crank-Nicolson method updates.
- [ ] Re-explain the tridiagonal solver more thoroughly.
- [ ] Show matrix version of differencing schemes that does account for boundary conditions.
- [ ] Add a warning box about the scoping issues that sometimes arise in the animation function.

If we're lucky, the weird scoping issues in the animations will go away in future versions of matplotlib. I don't know that we'll get that lucky though.

**Comment by shanemcq18** [comment]
@joshualy can you look at this? We can close it if it isn't up to date any more.

**Comment by joshualy** [comment]
@shanemcq18  Let's close this one. There certainly are changes that need to occur in this lab, but these comments probably aren't going in the right direction. What should really happen is Jeff should pull this material on conservation laws and heat flow into the textbook for Volume 4, along with a short discussion on the numerical method and its stability properties. This material is foundational, and shouldn't be left to the labs.
