### ISSUE TITLE
Remove Stray Files

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#672]
There are various stray files and folders throughout the repository. For example, https://github.com/byuimpact/numerical_computing/tree/develop/Algorithms/Complexity. Most of these files come from either careless adds or from incomplete cleanup of old versions of labs. We should clean them out much more thoroughly.

**Comment by shanemcq18** [comment]
Cleaning will take place this Spring and Summer as we go through Volume I and II carefully.
