### ISSUE TITLE
Floating point revisions

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#694]
The floating point labs are currently not included in Volumes 1 through 4, but, if they are ever used, I'd suggest the following revisions to the first one:

Since the fast square root and fast inverse square root algorithms are actually really cool, it would be really cool to focus that lab more on coding that algorithm. In practice that would mean removing the problem involving creating a floating point class and changing some of the code that is given to them into pseudocode. It would also be good to have them do the fast inverse square root instead of just the fast square root.

**Comment by shanemcq18** [comment]
#475 Also closed.
