### ISSUE TITLE
Profiling Techniques

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#739]
Here's an observation/idea that could be worth considering at some future date:
The discussion of profiling in the profiling lab is fairly minimal. There are more advanced techniques available. It could be wise to add a lengthier discussion of line profiling and profiling Cython code.
Cache locality and memory layout of NumPy arrays could be mentioned there, though it still wouldn't really fit as a core topic.

**Comment by ayr0** [comment]
Somewhere along the line, too much was cut from the profiling lab.  Profiling is now simply glossed over, which is not the way I remember the original lab being written.

**Comment by ayr0** [comment]
Some good ideas for further the profiling lab, and possibly splitting it again.
http://www.huyng.com/posts/python-performance-analysis/
Memory profiling would be an interesting addition.

**Comment by shanemcq18** [comment]
@tkchris93 thoughts?
