### ISSUE TITLE
"Additional Material" sections in labs

### ISSUE THREAD

**Issue by ayr0** [Foundations-of-Applied-Mathematics/Labs#764]
Lots of good content has been stripped from the beginning labs because they became too long.  The content, however, is still important and should be available somewhere as a supplement or appendix.

I propose that instead of commenting out material in labs and forcing a 2 hour time limit, that extra material be moved to a separate section of the lab for supplemental, optional material.  That way, a 2 hour time limit can still be feasible, but important information could also be presented for those interested in reading it.  I think this would prove a more flexible approach in general.

**Comment by shanemcq18** [comment]
We'll revisited / discus this as we start combing through Vols I and II in the next few weeks.

**Comment by shanemcq18** [comment]
Approved by Jeff.
