### ISSUE TITLE
Feedback for Standard Library lab

### ISSUE THREAD

**Issue by tkchris93** [Foundations-of-Applied-Mathematics/Labs#784]
As a whole, I liked the lab a lot.  The way the lab is structured, it takes a big problem and separates it into bite-size pieces.

The only part that tripped me up was handling the tributes list in Problem 7.  The first time I tried it, I tried removing deceased tributes from the tributes list directly, but then that caused indexing errors in my for-loop.  In the end, I ended up using a deque and rotating the first element.  I went back through the lab again a few weeks later and realized that a lot of the things I had done the first time were not efficient.  Had I been more thorough in reading what’s written in the lab, I don’t think I would have ran into the problems I did.

It took me 4.5 hours to complete this lab.  I spent a lot of time trying to parse the files using strategies learned in CS 142 instead of the using the methods unique to Python.  I think had I been more careful about what I was reading and had a took a few more minutes to think about the pseudocode before jumping into the problem, I could’ve saved lots of time.  

Referencing the version of this lab currently on the ACME website, the first paragraph of page 12 was a little confusing for me. I think something like this would make it a bit more clear: “However, we see a huge difference in the execution time of these two functions when we iterate through each of them.  Iterating through the first function requires 1.43ms.  Iterating through the generator requires a mere .00000041ms!  The reason…”

In Problem 3, there is a chance that students new to Python won’t know how to return multiple variables from one function.

In Problem 7, I think it could be more clear that you want the output file to be dependant on the console input by changing “output.txt” in the code box to a variable named output_file.  Then the following sentence could be rewritten as “The variable output_file should be the name of the file…”

**Comment by ayr0** [comment]
Some comments:  You can't change the datastructure you are iterating over.  Doing so will invalidate the iterator.  I'm not aware of any language where modifying a datastructure while iterating through it is considered good practice.

In regard to iterating through generators.  If you read the paragraph more carefully, you will notice that it is referring to the setup cost of the iteration.  The actual iteration takes the same amount of time in both cases, but setting up a generator object is much faster than creating a list to iterate over.

Problem3: Returning multiple values in Python is the same as almost any other language.  You are actually only returning a single tuple with multiple values in it.  In C++, you would allocate a fixed-length array, fill it with the results and return the array.

**Comment by shanemcq18** [comment]
The next iteration of this lab will be reviewed shortly.
