### ISSUE TITLE
Port old matlab code

### ISSUE THREAD

**Issue by insertinterestingnamehere** [Foundations-of-Applied-Mathematics/Labs#99]
There is some old matlab code included as either to generate figures or provide solutions for some of the old labs. This should be ported to Python and the figures should be regenerated. This isn't a critical change, but it should be done at some point.

**Comment by shanemcq18** [comment]
Update: currently the only labs that have .m files are BarycentricInterpolation and Broyden. Both of these have been orphaned and put into the textbook, but I'll look at them more closely before closing this issue.
